### PR TITLE
Run CircleCI builds on tag pushes

### PR DESCRIPTION
**Pull request by jgershen**

### CODE REVIEW

**Comment by hankim813** [comment]
@jgershen do we still need this?

**Comment by jgershen** [comment]
It would be nice to have for consistency of deploy process! IIRC the tests were broken on master?

**Comment by hankim813** [comment]
@jgershen yeah I think all these PRs failed because of master failing. Circle doesn't run builds on tag pushes? That's strange...

**Comment by ndhoule** [comment]
Superseded by #38

**Pull request closed without merging**
